defaults:
  - settings_schema


_tags_: ~

epochs: 30

optimizer: ADAM
learning_rate: 0.01
momentum: ~
milestones: ~
scenario: INC_TASK
strategy: Interval

interval:
  robust_accuracy_threshold: 0.9
  robust_lambda: 0.002
  radius_multiplier: 1.0
  max_radius: 1.0
  radius_exponent: 0.5
